name: Build EXE

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*" # Führt die Action aus, wenn du z. B. einen Tag "v1.0.0" pushst

jobs:
  build:
    runs-on: windows-latest  # Wir brauchen Windows, um eine .exe zu bauen
    permissions:
      contents: write        # Erlaubt dem Bot, überhaupt ein Release in deinem Repo anzulegen


    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        # --onefile packt alles in eine Datei
        # --noconsole verhindert das schwarze Fenster (optional)
        pyinstaller --onefile --name "TerminBot" --hidden-import="selenium.webdriver.firefox.options" --hidden-import="selenium.webdriver.firefox.service" --hidden-import="selenium.webdriver.firefox.webdriver" --hidden-import="webdriver_manager.firefox" --hidden-import="selenium.webdriver.common.by" --hidden-import="selenium.webdriver.support.ui" --hidden-import="selenium.webdriver.support.expected_conditions" --hidden-import="selenium.webdriver.common.action_chains" check_and_book.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TerminBot-Exe
        path: dist/TerminBot.exe
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/TerminBot.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}